trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ServiceNow-DevOps-Server-Change-Acceleration@1
  inputs:
    connectedServiceName: 'SnowLab'
    toolId: 'AzureDevOps'
    jobName: 'Deploy-App'

- script: |
    echo "Executando deploy"